logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.r2dbc: DEBUG

spring:
  data:
    repositories:
      enabled: true
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  r2dbc:
    url: r2dbc:h2:mem://./testdb
    username: student
    password:
  thymeleaf:
    cache: false

springdoc:
  show-actuator: true
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui