logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.r2dbc: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true
  r2dbc:
    url: r2dbc:h2:mem://./testdb
    username: student
    password:
  thymeleaf:
    cache: false
    mode: HTML
  
  auth:
    base64-secret: OTUyNDMyY2NlN2QwN2MyMmI5MmVkMWU1NGE1NjUxMjdlYjQ3OGJlMTExZjdhOTZmMmUxMzg3MmEzYzc2ODIyYzVkYTRjYmYwODFjZjIwMGVjYTljOWFiZmZkOWQyYjAyNzIwNmUyMGNkMDkzMWZjNjk2NWM3ZGNhZDkxMjNjNTM=
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000

springdoc:
  show-actuator: true
  api-docs:
    enabled: true

#    Me12345

app:
  firebase:
    key: AIzaSyCt9RtnfJqnv2mlKLlprp0ItGI-5qMWM44