logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.r2dbc: DEBUG

spring:

  jackson:
    serialization:
      indent-output: true
  r2dbc:
    url: r2dbc:h2:mem://./testdb
    username: student
    password:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: file:src/main/resources/templates/

springdoc:
  show-actuator: true
  api-docs:
    enabled: true